Repository openpharma/visR, pull requests merged in 2021-03, with the labels that each got.

#128 add_CNSR.R - additional examples
  R/add_CNSR.R
Labels: documentation

#130 get_pvalue - additional examples added
  R/get_pvalue.R
Labels: documentation

#127 add_CI - update examples and fix API change in examples
  man/add_CI.Rd
Labels: documentation

#126 Added missing tests for warning/error behaviour. Should raise test coverage to 100% for CI and CNSR.
  R/add_CI.R
  R/add_CNSR.R
  R/testthat_helpers.R
  tests/testthat.R
  tests/testthat/test-add_CI.R
  tests/testthat/test-add_CNSR.R
Labels: enhancement, testing

#136 Removed one useless sanity check in add_CNSR.R; Added test for warning when style=ribbon with linetype specified
  R/add_CNSR.R
  tests/testthat/test-add_CI.R
Labels: testing

#139 Doc/km vignette review
  vignettes/Time_to_event_analysis.Rmd
Labels: documentation

#142 Update add_ci & add_cnsr document + examples
  R/add_CI.R
  R/add_CNSR.R
Labels: documentation

#129 estimate_KM
  R/estimate_KM.R
Labels: documentation

#125 Review documentation add_annotation
  R/add_annotation.R
Labels: documentation

#132 Documentation for plot function
  DESCRIPTION
  R/plot.R
Labels: documentation, issue, question

#145 doc and examples for tableone
  R/tableone.R
Labels: documentation

#131 Documentation for get_tableone
  R/get_tableone.R
Labels: documentation
